# Generated by Django 2.2.5 on 2020-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0002_auto_20200502_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercontents',
            name='about',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownercontents',
            name='coverImg',
            field=models.ImageField(blank=True, null=True, upload_to='author_img'),
        ),
    ]
