# Generated by Django 2.2.5 on 2020-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0003_auto_20200504_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercontents',
            name='about',
            field=models.CharField(blank=True, default='hello', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ownercontents',
            name='coverImg',
            field=models.ImageField(blank=True, default='author_profile/dasfdad.png', null=True, upload_to='author_img'),
        ),
    ]
