# Generated by Django 2.2.5 on 2020-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0004_auto_20200504_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercontents',
            name='coverImg',
            field=models.ImageField(blank=True, default='author_profile/dasfdad.png', upload_to='author_img'),
        ),
    ]
