# Generated by Django 2.2.5 on 2020-05-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0006_auto_20200504_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='contentlenth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='postcreate',
            name='contentlock',
            field=models.BooleanField(default=False),
        ),
    ]
