# Generated by Django 2.2.5 on 2020-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0008_postcreate_contentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='Persentase',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
