# Generated by Django 2.2.5 on 2020-06-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0009_postcreate_persentase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='mobilebrand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Data_app.Cetagroy_list'),
        ),
    ]
