# Generated by Django 2.2.5 on 2020-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0010_auto_20200603_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='reviewcount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
