# Generated by Django 2.2.5 on 2020-06-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0011_postcreate_reviewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='mobilebrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_app.Cetagroy_list'),
        ),
    ]
